name: Cl

on: [push]

jobs:
  Cl:
    name: Lint Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Node v16
        uses: actions/setup-node@v2
        with:
          node-version: "16.13.0"
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Check Lint
        run: npm run lint
